-- ============================================================================
-- Max-tier features: Share links + AI handouts.
--
-- share_links
--   Per-recording short-code URLs that let a recipient replay the recording
--   in a public web player. Reuses the bytes already stored under
--   storage.objects/recordings/{user_id}/{recording_id}/ —— we just sign URLs
--   from the public route. Default TTL 30 days.
--
-- handouts
--   AI-generated outline + Markdown handout per recording. One row per
--   recording (unique on recording_id). Generated by /api/handout/generate
--   via Deepseek.
--
-- All writes are gated through API routes that check tier === 'max' against
-- pro_subscriptions; RLS denies direct writes from authenticated role.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- share_links
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.share_links (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  short_code    text UNIQUE NOT NULL,
  recording_id  uuid NOT NULL,
  user_id       uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at    timestamptz NOT NULL DEFAULT now(),
  expires_at    timestamptz NOT NULL,
  access_count  integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_share_links_short_code
  ON public.share_links (short_code);
CREATE INDEX IF NOT EXISTS idx_share_links_user
  ON public.share_links (user_id, created_at DESC);

ALTER TABLE public.share_links ENABLE ROW LEVEL SECURITY;

-- Owner can list their own links.
CREATE POLICY share_links_self_read
  ON public.share_links
  FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

-- INSERT / UPDATE / DELETE go through service-role API routes (which check
-- tier === 'max'). No direct write policy for authenticated users.

-- ---------------------------------------------------------------------------
-- handouts
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.handouts (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recording_id  uuid NOT NULL,
  user_id       uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  outline       jsonb NOT NULL,
  markdown      text NOT NULL,
  model         text NOT NULL,
  generated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_handouts_recording
  ON public.handouts (recording_id);
CREATE INDEX IF NOT EXISTS idx_handouts_user
  ON public.handouts (user_id, generated_at DESC);

ALTER TABLE public.handouts ENABLE ROW LEVEL SECURITY;

-- Owner can read their own handouts.
CREATE POLICY handouts_self_read
  ON public.handouts
  FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

-- INSERT / UPDATE / DELETE via service-role API routes (tier === 'max').
